import React from 'react';
import Counter from '../Counter';
import ContentStyle from "./styles.module.css"


export default function Context(){

    return (
        <div className={ContentStyle.contentContainer}> 
            <h1 className="">
                Content
            </h1>
                <Counter />
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pellentesque consequat ipsum, eget tristique lectus ultricies at. Morbi massa massa, pellentesque at ex a, ornare tempus ipsum. Nullam congue metus at pharetra maximus. Sed facilisis nisl et pretium imperdiet. Sed non porttitor nibh. Nulla non odio ut purus dapibus pretium et quis enim. Aliquam malesuada mattis nulla. Vestibulum varius ligula mollis, malesuada justo in, placerat massa. Curabitur molestie diam tincidunt, sollicitudin erat a, mattis odio. Duis gravida nisl turpis, quis ultricies massa accumsan ut. Suspendisse nec risus ac ipsum tincidunt vestibulum et non nulla. Etiam a orci a felis elementum porta at eget purus.

Donec auctor lacus sem, quis sagittis tellus malesuada eget. Cras et laoreet risus, eget fermentum est. Mauris nec velit diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nisi ipsum, commodo in tempor eu, eleifend et enim. Curabitur malesuada tellus eget lorem sagittis tempus. Cras tincidunt, est a feugiat tempus, velit ligula efficitur ante, sed cursus est sapien ac nisi. Suspendisse viverra, ex eu sagittis lacinia, nibh ipsum efficitur massa, in rhoncus diam ex non elit. Donec nibh magna, posuere pharetra pulvinar vitae, tincidunt a est. Donec eros tortor, lobortis vitae congue eget, varius ullamcorper quam. Ut volutpat vehicula enim non lacinia. Integer interdum velit nisl, in maximus orci eleifend sit amet.

Quisque quis nisl vitae felis sagittis blandit. Nam non neque ac ante pretium eleifend. Ut consequat purus ut ex semper pharetra. Etiam dignissim, eros in consequat ultrices, sapien ante tincidunt lacus, a luctus mi libero eu est. Mauris blandit risus non ex cursus rhoncus. Suspendisse vitae aliquet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam ipsum neque, tincidunt ut nibh eget, consectetur fermentum dui. Suspendisse suscipit quam nec lectus laoreet, a semper arcu laoreet. Aliquam lorem nisi, porttitor eget orci eget, aliquam ultricies dolor. Sed feugiat iaculis tincidunt. Maecenas suscipit lorem a hendrerit gravida. Curabitur aliquet velit lectus, quis eleifend est lobortis ac. Vivamus eget velit elementum velit mattis rutrum. Praesent condimentum rhoncus imperdiet.

Praesent lorem nisl, sollicitudin eget nulla in, rhoncus fermentum mi. Vivamus ullamcorper, urna quis malesuada elementum, magna tortor finibus magna, venenatis iaculis risus lectus eu risus. Etiam scelerisque felis eu malesuada fringilla. Integer enim nisl, sollicitudin et felis a, sollicitudin venenatis elit. Morbi elementum tristique tellus, sed dictum turpis faucibus eu. Ut vitae velit justo. Mauris sit amet vestibulum mi. Duis vel velit a dui placerat scelerisque eu sed mauris. Sed nec tristique mauris. Vivamus molestie diam et elit pellentesque venenatis.

Donec vehicula justo id consectetur viverra. Donec velit ex, commodo nec risus et, pulvinar mollis erat. Mauris rutrum convallis vehicula. Pellentesque elementum lectus nisl, at sodales est varius sed. Praesent quis ligula vel enim molestie sodales. Nam dapibus posuere tortor quis varius. Pellentesque finibus consequat convallis. Nulla non ex vitae ipsum condimentum interdum.

Maecenas id felis a arcu suscipit ultrices eget nec nisl. Suspendisse libero lacus, lobortis aliquet odio venenatis, pretium ornare odio. Proin tellus orci, iaculis vel ultricies a, vulputate quis leo. Aliquam porttitor sem lorem, nec dapibus orci auctor nec. Vestibulum lacus urna, sodales mollis neque sit amet, vulputate pulvinar mauris. Cras placerat, justo eget aliquam varius, est purus facilisis nibh, eget hendrerit erat sapien quis augue. Donec auctor eu arcu a consequat. Nulla a facilisis nunc. Morbi tellus sapien, commodo a est vitae, bibendum ultrices est. Maecenas blandit neque a tellus suscipit, sed dictum purus scelerisque. Fusce auctor fermentum venenatis. Ut mollis massa leo, vitae interdum nisl efficitur in. Sed et massa dui. Nam leo risus, tempor sit amet dapibus id, cursus a nisl. Sed nec mauris purus. Nullam ac lorem ut lectus finibus convallis.

Sed ligula dui, egestas eget nibh in, hendrerit semper diam. Curabitur aliquet mauris eget dolor ultrices blandit. Integer urna quam, commodo venenatis dolor in, posuere condimentum ligula. Aliquam sit amet augue massa. In aliquet tempor eros a molestie. Aliquam accumsan nunc ligula, eget posuere urna scelerisque nec. Ut interdum tortor nibh, vitae faucibus nisl varius ac. Cras condimentum placerat erat eget ullamcorper.

Vivamus nec leo nec purus tincidunt hendrerit in ut lorem. Nunc id magna vel lorem finibus rutrum. Phasellus ac sem placerat, pulvinar eros vel, placerat sapien. Mauris vulputate dapibus urna, vestibulum porta enim aliquam ut. Nunc sit amet elit ultricies, vestibulum neque id, ultrices enim. Cras maximus diam id ante aliquet tempor. Pellentesque luctus mi eget quam mattis pharetra. Aliquam laoreet magna vel elit egestas commodo. Fusce nec dui tortor. Donec nec est feugiat, dapibus diam sed, iaculis mi. Donec non justo sit amet augue efficitur elementum.

Sed at cursus elit. Curabitur non rhoncus erat. Nam facilisis rutrum sem, id vestibulum massa molestie vitae. Nulla porta pulvinar erat ac hendrerit. Cras eu dolor vel libero mattis posuere. In hac habitasse platea dictumst. Integer tincidunt, ante mattis viverra eleifend, sem massa dictum risus, a bibendum enim elit in velit. Vivamus vitae finibus libero, ac molestie dolor. Pellentesque quis tellus id nunc iaculis iaculis at quis elit. Fusce nec arcu dictum, mollis lorem dignissim, semper urna. Donec sapien sapien, sodales et justo sit amet, ullamcorper aliquet turpis. Nunc quis molestie dui, vel mattis ex. Etiam rutrum eros quam, a sollicitudin enim tempus eu. Quisque pulvinar accumsan dolor quis consequat. Vestibulum vel diam nisi. In nulla ante, luctus at est vitae, tristique fringilla dolor.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla diam sapien, ultrices non pharetra id, eleifend sed dolor. Pellentesque eget justo elit. Integer sit amet nisi semper, eleifend magna finibus, eleifend enim. Phasellus aliquet id tortor vel venenatis. Pellentesque diam lectus, porta non tortor eu, varius cursus lacus. Maecenas eu sollicitudin magna. Quisque fermentum dui id nibh fermentum consequat. Maecenas ac tellus at neque pellentesque laoreet.</p>
        </div>
    )
}